/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author jyoti
 */
public class Adminlogin extends javax.swing.JDialog {
       
Connection Conn ;
Statement stmt;
    /**
     * Creates new form
     */
    public Adminlogin(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        this.setTitle("CAT | Admin Login");
        
          try {   
        
        try{Class.forName("com.mysql.jdbc.Driver").newInstance();
        
        }catch(ClassNotFoundException |InstantiationException |IllegalAccessException q)
        {
            ;
        } 
        
        String url = "jdbc:mysql://localhost:3306/cat?zeroDateTimeBehavior=convertToNull";
        
        String user = "root";
        String pw = "vaibhav";
        
        
        
                
      //  System.out.println(insert);
         Conn = DriverManager.getConnection( url, user, pw );
        stmt  = Conn.createStatement();
   
          }catch(SQLException sqle)
    {
           //System.out.println("SqlException:" + sqle);
    }
    
        
        
        
        
        this.setLocationRelativeTo(null);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Login");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Administrator Login");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("UserID");

        jTextField1.setText("username");
        jTextField1.setSelectionStart(0);

        jPasswordField1.setText("password");
        jPasswordField1.setSelectionStart(0);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String gettext_tf()
    {
    
    String s1 = jTextField1.getText();
    return s1;
    }
    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        
        char  s2[] = jPasswordField1.getPassword();
        String entered_pass = new String(s2);
       System.out.println(entered_pass);
	String	s1 = jTextField1.getText();
        String  check_password = "select password from administrator where username ='"+s1+"'and password = md5('"+entered_pass+"')";
        
        try{
           ResultSet rs =  stmt.executeQuery(check_password);
              if(!rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Invalid username or password");
                }
              else
                {
             this.setVisible(false);
            NewJFrame2admin n =  new NewJFrame2admin(); //.setVisible(true); 
            String s = this.gettext_tf();
            //System.out.println(s);
            n.setVisible(true);
            n.take(s);          
                }
        
                }catch( SQLException w){
                    JOptionPane.showMessageDialog(null, w);
                }
        
        
        
        
       // char[] correctPassword = { 'i', 'c', 'e', 'c', 'r', 'e', 'a', 'm' };

   
      
        
        
        
        
        
        
        
        
//                if("vaibhav".equals(s1) || "pratik".equals(s1)|| "vibhav".equals(s1))
//        {
//            if(s2[0] == 'i' && s2[1] == 'c' && s2[2] == 'e' && s2[3] == 'c' && s2[4] == 'r'&& s2[5] == 'e' && s2[6] == 'a' && s2[7] == 'm')
//            {
//            s2[0] = 0;
//            s2[1] = 0;
//            s2[2] = 0;
//            s2[3] = 0;
//            s2[4] = 0;
//            s2[5] = 0;
//            s2[6] = 0;
//            s2[7] = 0;
//            this.setVisible(false);
//            NewJFrame2admin n =  new NewJFrame2admin(); //.setVisible(true); 
//            String s = this.gettext_tf();
//            //System.out.println(s);
//            n.setVisible(true);
//            n.take(s);
//            }
//            else
//            {
//            JOptionPane.showMessageDialog(null, "Wrong Password");
//            
//            }
//        }
//        else{                  
//                    
//                    
//                    
//                    
//                    
//                    
//                    
//                    
//                    
//                    JOptionPane.showMessageDialog(null, "Wrong username");
//        }
		

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Adminlogin dialog = new Adminlogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
