/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



 package javaapplication1;
import java.awt.Color;
import java.util.regex.*;
 import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.Font;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JInternalFrame;
 

/**
 *
 * @author jyoti
 */
public class NewJFrame1 extends javax.swing.JFrame {
    
         Pattern frstnamepat,lastnamepat,cellpat,collegepat,emailpat ;
       Matcher frstnamematch,lastnamematch,cellmatch,collegematch,emailmatch;
   String Fname,Cell,Lname,College,Email,Reg_id;
   private static final DateFormat dateFormat = new SimpleDateFormat(
			"dd/MM/yyyy HH:mm:ss");
 
   
   
   public static final   String NAME_PATTERN = "^[a-zA-Z]{3,20}$";
   public static final   String CELL_PATTERN = "[-+\\d() ]{9,11}"; 
   public static final   String COLLEGE_PATTERN = "^[a-zA-Z.0-9-]{2,20}";
   public static final   String EMAIL_PATTERN = "";
      
   
   public NewJFrame1() {
       Font font = new Font("Tmes New Roman", Font.ITALIC, 20);
       
       
        initComponents();
        
        
        
        this.setTitle(" Personal Details Form");
        this.setLocationRelativeTo(null);
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TextFname = new javax.swing.JTextField();
        TextLName = new javax.swing.JTextField();
        TextCell = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        TextCollege = new javax.swing.JTextField();
        TextRegId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form");
        setBackground(new java.awt.Color(246, 124, 124));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setLabelFor(TextFname);
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setLabelFor(TextLName);
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setLabelFor(TextEmail);
        jLabel3.setText("Contact No");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setLabelFor(TextCollege);
        jLabel4.setText("Email id");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setLabelFor(TextEmail);
        jLabel5.setText("College");

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Admin login!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel7.setText("Personal Details Form");

        jButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TextFname.setText(" ");
        TextFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFnameActionPerformed(evt);
            }
        });

        TextLName.setText(" ");

        TextCell.setText(" ");
        TextCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCellActionPerformed(evt);
            }
        });

        TextEmail.setText(" ");

        TextCollege.setText(" ");

        TextRegId.setText(" ");

        jButton4.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jButton4.setText("I've verified the details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Reg Id");

        jLabel9.setText("+91");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextLName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextFname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextCell, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(133, 133, 133))
                        .addComponent(TextRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextRegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addContainerGap())
        );

        TextFname.getAccessibleContext().setAccessibleName("Labelfirstname");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //        SQL ConnectivityCode
        
  //  String query = "insert into applicant values (" + Fnam;
    try {   
        
        try{Class.forName("com.mysql.jdbc.Driver").newInstance();
        
        }catch(ClassNotFoundException |InstantiationException |IllegalAccessException q)
        {
            ;
        } 
        
        String url = "jdbc:mysql://localhost:3306/cat?zeroDateTimeBehavior=convertToNull";
        
        String user = "root";
        String pw = "vaibhav";
        String insert;
        insert = "insert into applicant values(' "
                +Reg_id+
                "','"
                +Fname+
                "','"
                +Lname+
                "','"
                +Cell+
                "','"
                +Email+
                "','"
                +College+
                "',NULL,'"
                +getCurrentTimeStamp()+
                 "')";
                
        //System.out.println(insert);
        Connection Conn = DriverManager.getConnection( url, user, pw );
        Statement stmt  = Conn.createStatement();
        stmt.executeUpdate(insert);
       
    }
    catch(SQLException sqle)
    {
           JOptionPane.showMessageDialog(null, "A record with this Registration ID was already found. You cannot give the test more than once.");
           jButton3ActionPerformed(evt);
           return;
           
    }
//System.out.println(getCurrentTimeStamp());
      
      this.dispose();
     NewJFrame ques_frame =  new  NewJFrame();
      Reg_id = TextRegId.getText();
     // System.out.println(Reg_id);
      ques_frame.Fetch_regid(Reg_id);
      ques_frame.setVisible(true);

        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
private static String getCurrentTimeStamp() {
 
		java.util.Date today = new java.util.Date();
		return dateFormat.format(today.getTime());
 
	}
    private void TextFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String t = " ";
        TextFname.setText(t);
        TextLName.setText(t);
        TextCell.setText(t);
        TextEmail.setText(t);
        TextCollege.setText(t);
        TextRegId.setText(t);
        jButton1.setEnabled(false);
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void TextCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCellActionPerformed
      
        
       
    }//GEN-LAST:event_TextCellActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
  new  Adminlogin(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

     public boolean validatefname(final String username){
 
		  frstnamematch = frstnamepat.matcher(username);
		  return frstnamematch.matches();
 
	  }
    
     
     public boolean validatelname(final String username){
 
		  lastnamematch = lastnamepat.matcher(username);
		  return lastnamematch.matches();
 
	  }
    
    public boolean validatecell(final String username){
 
		  cellmatch = cellpat.matcher(username);
		  return cellmatch.matches();
 
	  }
     
     public boolean validatecollege(final String username){
 
		  collegematch = collegepat.matcher(username);
		  return collegematch.matches();
 
	  }
     
     public boolean validateemail(final String username){
 
		  emailmatch = emailpat.matcher(username);
		  return emailmatch.matches();
 
	  }
     
     
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
        int flag = 1;
        
         frstnamepat = Pattern.compile(NAME_PATTERN);
         lastnamepat = Pattern.compile(NAME_PATTERN);
         cellpat = Pattern.compile(CELL_PATTERN);
         collegepat = Pattern.compile(COLLEGE_PATTERN);
         emailpat = Pattern.compile(EMAIL_PATTERN);
         
         Fname = TextFname.getText();
         Lname = TextLName.getText();
         Cell = TextCell.getText();
       
         Email = TextEmail.getText();
         College = TextCollege.getText();
         Reg_id = TextRegId.getText();
         
             
//         if(validatefname(Fname) == false)
//         {
//             JOptionPane.showMessageDialog(null, "enter proper First name");
//             TextFname.setText(" ");
//             flag = 0;
//         }
//         
//          if(validatelname(Lname) == false)
//         {
//             JOptionPane.showMessageDialog(null, "enter proper Last name");
//             TextLName.setText(" ");
//             flag = 0;
//         }
//         
         
//         
//        
         
//else if(validatecollege(College) == false)
//         {
//             JOptionPane.showMessageDialog(null, "enter proper College name");
//             TextCollege.setText(" ");
//             flag = 0;
//         }
//         
//          if(validateemail(Email) == false)
//         {
//             JOptionPane.showMessageDialog(null, "enter proper email address");
//             TextEmail.setText(" ");
//             flag = 0;
//         }

         
         int flagx = 0;
         if(" ".equals(Reg_id)){
//         {
//             JOptionPane.showMessageDialog(null, "Registration ID field is blank. Please enter the Registration ID provided to you.");
//            TextRegId.setText(" ");
//            flag = 0;
//         }
//         else if(" ".equals(Reg_id) == false)
         flagx = 1;
         try{
         double x = Double.parseDouble(Reg_id);
         }
         catch(NumberFormatException num)
         {
             JOptionPane.showMessageDialog(null, "Registration ID field is blank. Please enter the Registration ID provided to you.");
            TextRegId.setText(" ");
            flag = 0;
         }
         }
        
         
         else if(" ".equals(Fname)){
         JOptionPane.showMessageDialog(null, "First name field is blank. Please enter your first name.");
         TextFname.setText(" ");
         flag = 0;
         }
         
         else if(" ".equals(Lname)){
         JOptionPane.showMessageDialog(null, "Last name field is blank. Please enter your last name.");
         TextLName.setText(" ");
         flag = 0;
         }
         
         else if((Cell.length() == 10))
         {  
                 JOptionPane.showMessageDialog(null, "Contact number must contain exactly 10 digits.");
         }
             else if((validatecell(Cell) == false)){
             JOptionPane.showMessageDialog(null, "Invalid contact number. Please enter the number again.");
             TextCell.setText(" ");
             flag = 0;
         }
         
         
         else if(" ".equals(Email)){
         JOptionPane.showMessageDialog(null, "Email Id field is blank. Please enter the appropriate email id.");
         TextEmail.setText(" ");
         flag = 0;
         }
         
         else if(Email.contains("@") == false || Email.contains(".") == false)
         {
             int index = Email.indexOf("@");
             String afterat = Email.substring(index + 1);
             if (!afterat.contains("."))
             {
                 JOptionPane.showMessageDialog(null, "Invalid email id format. Please enter the appropriate email id.");
                 flag = 0;
             }
             
             
         }
          
         
         else if(" ".equals(College)){
         JOptionPane.showMessageDialog(null, "College field is blank. Please enter the your college name.");
         TextCollege.setText(" ");
         flag =0;
         }
         
         if (flagx == 0)
         {
         try{
         double x = Double.parseDouble(Reg_id);
         }
         catch(NumberFormatException num)
         {
             JOptionPane.showMessageDialog(null, "Invalid characters in Registration ID.");
            TextRegId.setText(" ");
            flag = 0;
         }
         }    
         
         
   
//             
             
             
             //             else{
//             try{double  k = Double.parseDouble(Cell);}
//             catch(NumberFormatException r){
//                 JOptionPane.showMessageDialog(null, " please enter nos only in cell no.");
//                 flag = 0;
//                 TextCell.setText(" ");
//             }
   //          }
                        
             if(flag ==1){
                jButton1.setEnabled(true);           
         }
         
         
         

//        java.util.Date date= new java.util.Date();
//	Timestamp time = new Timestamp(date.getTime());
             
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
		}//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCell;
    private javax.swing.JTextField TextCollege;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextFname;
    private javax.swing.JTextField TextLName;
    private javax.swing.JTextField TextRegId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
