/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jyoti
 */
public class ViewQuestions extends javax.swing.JFrame {

    int level_selected = 1;
    public static Statement stmt;
    public static Connection Conn;
    
        

   
   //  * Creates new form ViewQuestions
     //* 
    public ViewQuestions() {
        initComponents();
        this.setTitle("CAT | View Questions");
        this.setLocationRelativeTo(null);
        String user="root";
        String pw = "vaibhav";
        question_table.setVisible(false);
        try{
           Class.forName("com.mysql.jdbc.Driver").newInstance();
         }catch(ClassNotFoundException |InstantiationException |IllegalAccessException q)
        {
            ;
        } 
        try{
        String url = "jdbc:mysql://localhost:3306/cat?zeroDateTimeBehavior=convertToNull";
        Conn = DriverManager.getConnection( url, user, pw );
        Conn.setAutoCommit(true);
        this.stmt  = Conn.createStatement();
        }
        catch(SQLException sqle)
    {
           //System.out.println("SqlException:" + sqle);
    }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        level_selector = new javax.swing.JComboBox();
        button_view = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        question_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        qcode_tf = new javax.swing.JTextField();
        label_qcode_selected = new javax.swing.JTextField();
        button_quit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Question Database");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Selected Question Code");

        level_selector.setMaximumRowCount(10);
        level_selector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        level_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level_selectorActionPerformed(evt);
            }
        });

        button_view.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_view.setText("View");
        button_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewActionPerformed(evt);
            }
        });

        button_delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_delete.setText("Delete question");
        button_delete.setToolTipText("Select a question code to delete from the table");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        question_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question Code", "Question", "Option1", "Option2", "Option3", "Option4", "Correct Answer", "No of attempts", "Correct Attempts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        question_table.setColumnSelectionAllowed(true);
        question_table.setGridColor(new java.awt.Color(0, 255, 0));
        question_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        question_table.getTableHeader().setReorderingAllowed(false);
        question_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                question_tableMouseClicked(evt);
            }
        });
        question_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                question_tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(question_table);
        question_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        question_table.getColumnModel().getColumn(1).setPreferredWidth(160);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Choose level");

        qcode_tf.setEditable(false);
        qcode_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qcode_tfActionPerformed(evt);
            }
        });

        label_qcode_selected.setEditable(false);
        label_qcode_selected.setText("None");

        button_quit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        button_quit.setForeground(new java.awt.Color(0, 51, 255));
        button_quit.setText("Quit");
        button_quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_quitMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("Modify Question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 431, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(level_selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(button_view)))
                        .addGap(412, 412, 412))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(label_qcode_selected, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(button_delete)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_quit)
                        .addGap(24, 24, 24))))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(509, 509, 509)
                    .addComponent(qcode_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level_selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_view)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_delete)
                    .addComponent(jLabel2)
                    .addComponent(label_qcode_selected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_quit)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(qcode_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewActionPerformed
        question_table.setVisible(true);
        label_qcode_selected.setText("None");
        //((DefaultTableModel)question_table.getModel()).setRowCount(0);
        
        level_selected = level_selector.getSelectedIndex() + 1;
        //   System.out.println(level_selected);
        loadquestions(level_selected);
        ((DefaultTableModel)question_table.getModel()).setRowCount(25);
        //        question_table.set = "aaaa";
        // TODO add your handling code here:
    }//GEN-LAST:event_button_viewActionPerformed

    private void level_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level_selectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level_selectorActionPerformed

    private void qcode_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qcode_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qcode_tfActionPerformed

    private void question_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_question_tableMouseClicked
        //((DefaultTableModel)question_table.getModel()).setRowCount(0);
        
       
        int col_value = question_table.getSelectedColumn();
        try{
        if (col_value == 0)
        {
             int row_value = question_table.getSelectedRow();
             int qcode = (int) question_table.getValueAt(row_value, col_value);
             label_qcode_selected.setText(Integer.toString(qcode));
        }
        else
        {
             label_qcode_selected.setText("None");
        }
        }
        catch(NullPointerException n){
            label_qcode_selected.setText("None");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_question_tableMouseClicked

    private void question_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_question_tableKeyReleased
        int col_value = question_table.getSelectedColumn();
        try{
        if (col_value == 0)
        {
             int row_value = question_table.getSelectedRow();
             int qcode = (int) question_table.getValueAt(row_value, col_value);
             label_qcode_selected.setText(Integer.toString(qcode));
        }
        else
        {
             label_qcode_selected.setText("None");
        }
        }
        catch(NullPointerException n){
            label_qcode_selected.setText("None");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_question_tableKeyReleased

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        
        if(label_qcode_selected.getText().equals("None") == false)
        {
        String del_query = "delete  from level"+Integer.toString(level_selected)+" where qcode="+label_qcode_selected.getText();
       // System.out.println(del_query);
        try{
            stmt.executeUpdate(del_query);
            loadquestions(level_selected);
        }
        catch(SQLException s)
        {
            ;
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No Question Code has been selected. Please select one and then press the Delete Question button.");
        }
        // TODO add your handling code here:
        label_qcode_selected.setText("None");
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_quitMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_button_quitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuestions().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_delete;
    private javax.swing.JLabel button_quit;
    private javax.swing.JButton button_view;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField label_qcode_selected;
    private javax.swing.JComboBox level_selector;
    private javax.swing.JTextField qcode_tf;
    private javax.swing.JTable question_table;
    // End of variables declaration//GEN-END:variables

    public void loadquestions(int level_selected) {
        ((DefaultTableModel)question_table.getModel()).setRowCount(0);
  try {   
        
        try{Class.forName("com.mysql.jdbc.Driver").newInstance();
        
        }catch(ClassNotFoundException |InstantiationException |IllegalAccessException q)
        {
            ;
        } 
        
        String url = "jdbc:mysql://localhost:3306/cat?zeroDateTimeBehavior=convertToNull";
        
        String user = "root";
        String pw = "vaibhav";
        String fetch_question = "select * from level"+Integer.toString(level_selected);
        
                
      //  System.out.println(insert);
        Connection Conn = DriverManager.getConnection( url, user, pw );
        Statement stmt  = Conn.createStatement();
        ResultSet rs = stmt.executeQuery(fetch_question);

        while(rs.next())
        {
            int qcode = rs.getInt(1);
            String question = rs.getString(2);
            String opt1 = rs.getString(3);
            String opt2 = rs.getString(4);
            String opt3 = rs.getString(5);
            String opt4 = rs.getString(6);
            int correct = rs.getInt(7);
            int attempts = rs.getInt(8);
            int correct_attempts = rs.getInt(9);
            
            ((DefaultTableModel)question_table.getModel()).addRow(new Object [] {qcode, question, opt1, opt2, opt3, opt4, correct, attempts, correct_attempts}); 
            
        }
     
//       ((DefaultTableModel)question_table.getModel()).addRow(new_row); 
      //here we will write code to load the questions
      //throw new UnsupportedOperationException("Not yet implemented");
    }
    catch(SQLException sqle)
    {
           //System.out.println("SqlException:" + sqle);
    }
    }
}
